language: go
go:
  - 1.x
install:
  - go get golang.org/x/lint
  - go get github.com/therealfakemoot/genesis
script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint ./...
  - go test -v -race ./...
